" vimrc
" Setting for vim that have been either disabled or set as default in neovim.

source ~/.dotphiles/vim/nvimrc

" Optimize for fast terminal connections
set ttyfast

" Sets how many lines of history VIM has to remember
set history=500

" Set to auto read when a file is changed from the outside
set autoread

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

" Mouse
if has("mouse")
    set mouse=a
endif

" Always show the status line
set laststatus=2

"Enable command line tab completion
set wildmenu

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set smarttab
set autoindent

" When searching try to be smart about cases
set smartcase

" Highlight searches as they are typed.
set incsearch
