export ZDOTDIR="$HOME/.dotphiles/zsh"

if [[ "$OSTYPE" == "darwin"* ]]; then
    # OSX

    export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
    export MANPATH=$HOME/.nix-profile/share/man:$MANPATH
else
    export PATH="$HOME/.dotphiles/bin:$PATH"
    # Non-OSX
fi

# Add nix
source "$HOME/.nix-profile/etc/profile.d/nix.sh"
