#!/usr/bin/env zsh
# -------------- #
#   ZSH Config   #
# -------------- #

# Path to your zsh configuration.
ZSH=$HOME/.dotphiles/zsh

# Use neovim instead of vim if installed or vi if all else fails
if hash nvim >/dev/null 2>&1; then
    export EDITOR=nvim
elif hash vim >/dev/null 2>&1; then
    export EDITOR=vim
else
    export EDITOR=vi
fi

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly dotphiles auto-update checks
# DOTPHILES_AUTO_UPDATE="false"

# Uncomment the following line to change how often to auto-update dotphiles (in days).
# export UPDATE_DOTPHILES_DAYS=13

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to
# be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load?
# (plugins can be found in ~/.dotphiles/zsh/plugins/*)
# Custom plugins may be added to ~/.dotphiles/zsh/custom/plugins/
plugins=(\
    colored-man-pages \
    virtualenvwrapper \
    zsh-completions \
)

# If OSX add these plugins as well.
if [[ "$OSTYPE" == "darwin"* ]]; then
    plugins+=( \
        brew \
        brew-cask \
        pod \
    )
fi

# Load plugins
source $ZSH/load-plugins.zsh

# Load Path
source $ZSH/path.zsh

# Load theme
source $ZSH/prompt.zsh

# Load Aliases
source $ZSH/aliases.zsh

# Check for dotphiles update
source $ZSH/update-dotphiles.zsh


# -------------- #
#    ENV VARS    #
# -------------- #

# Turn off less history
export LESSHISTFILE="-"

